In [1]:
import pandas as pd
import numpy as np
from numpy import *
import torch
import matplotlib.pyplot as plt
import time

In [2]:
data_length = 150

In [3]:
#pakai pandas
data_input = pd.read_csv('iris_input.csv', header = None)
data_target = pd.read_csv('iris_target.csv', header = None)
print ('Data input\n',data_input,'\nData target\n',data_target)

Data input
        0    1    2    3
0    5.1  3.5  1.4  0.2
1    7.0  3.2  4.7  1.4
2    6.3  3.3  6.0  2.5
3    4.9  3.0  1.4  0.2
4    6.4  3.2  4.5  1.5
5    5.8  2.7  5.1  1.9
6    4.7  3.2  1.3  0.2
7    6.9  3.1  4.9  1.5
8    7.1  3.0  5.9  2.1
9    4.6  3.1  1.5  0.2
10   5.5  2.3  4.0  1.3
11   6.3  2.9  5.6  1.8
12   5.0  3.6  1.4  0.2
13   6.5  2.8  4.6  1.5
14   6.5  3.0  5.8  2.2
15   5.4  3.9  1.7  0.4
16   5.7  2.8  4.5  1.3
17   7.6  3.0  6.6  2.1
18   4.6  3.4  1.4  0.3
19   6.3  3.3  4.7  1.6
20   4.9  2.5  4.5  1.7
21   5.0  3.4  1.5  0.2
22   4.9  2.4  3.3  1.0
23   7.3  2.9  6.3  1.8
24   4.4  2.9  1.4  0.2
25   6.6  2.9  4.6  1.3
26   6.7  2.5  5.8  1.8
27   4.9  3.1  1.5  0.1
28   5.2  2.7  3.9  1.4
29   7.2  3.6  6.1  2.5
..   ...  ...  ...  ...
120  5.0  3.5  1.3  0.3
121  5.5  2.6  4.4  1.2
122  6.7  3.1  5.6  2.4
123  4.5  2.3  1.3  0.3
124  6.1  3.0  4.6  1.4
125  6.9  3.1  5.1  2.3
126  4.4  3.2  1.3  0.2
127  5.8  2.6  4.0  1.2
128  5.8  2.7  5.1  1.9
129 

In [4]:
#ubah ke numpy (dalam matriks)
data_input_np = np.c_[data_input]
data_target_np = np.c_[data_target]
print('Data input dalam matriks\n',data_input_np,'\nData target dalam matriks\n',data_target_np)

Data input dalam matriks
 [[5.1 3.5 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.3 3.3 6.  2.5]
 [4.9 3.  1.4 0.2]
 [6.4 3.2 4.5 1.5]
 [5.8 2.7 5.1 1.9]
 [4.7 3.2 1.3 0.2]
 [6.9 3.1 4.9 1.5]
 [7.1 3.  5.9 2.1]
 [4.6 3.1 1.5 0.2]
 [5.5 2.3 4.  1.3]
 [6.3 2.9 5.6 1.8]
 [5.  3.6 1.4 0.2]
 [6.5 2.8 4.6 1.5]
 [6.5 3.  5.8 2.2]
 [5.4 3.9 1.7 0.4]
 [5.7 2.8 4.5 1.3]
 [7.6 3.  6.6 2.1]
 [4.6 3.4 1.4 0.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.5 4.5 1.7]
 [5.  3.4 1.5 0.2]
 [4.9 2.4 3.3 1. ]
 [7.3 2.9 6.3 1.8]
 [4.4 2.9 1.4 0.2]
 [6.6 2.9 4.6 1.3]
 [6.7 2.5 5.8 1.8]
 [4.9 3.1 1.5 0.1]
 [5.2 2.7 3.9 1.4]
 [7.2 3.6 6.1 2.5]
 [5.4 3.7 1.5 0.2]
 [5.  2.  3.5 1. ]
 [6.5 3.2 5.1 2. ]
 [4.8 3.4 1.6 0.2]
 [5.9 3.  4.2 1.5]
 [6.4 2.7 5.3 1.9]
 [4.8 3.  1.4 0.1]
 [6.  2.2 4.  1. ]
 [6.8 3.  5.5 2.1]
 [4.3 3.  1.1 0.1]
 [6.1 2.9 4.7 1.4]
 [5.7 2.5 5.  2. ]
 [5.8 4.  1.2 0.2]
 [5.6 2.9 3.6 1.3]
 [5.8 2.8 5.1 2.4]
 [5.7 4.4 1.5 0.4]
 [6.7 3.1 4.4 1.4]
 [6.4 3.2 5.3 2.3]
 [5.4 3.9 1.3 0.4]
 [5.6 3.  4.5 1.5]
 [6.5 3.  5.5 1.8]
 [5.1

In [5]:
#siap-siap normalisasi data
#masukkan tiap data ke masing-masing variabel
data_sl = data_input_np[:data_length,[0]]
data_sw = data_input_np[:data_length,[1]]
data_pl = data_input_np[:data_length,[2]]
data_pw = data_input_np[:data_length,[3]]

#cek hasil pemindahan
print('Data sepal length\n', data_sl)
print('\nData sepal width\n', data_sw)
print('\nData petal length\n', data_pl)
print('\nData petal width\n', data_pw)

#cari maksimum
max_sl = max(data_sl)
max_sw = max(data_sw)
max_pl = max(data_pl)
max_pw = max(data_pw)

#cari minimum
min_sl = min(data_sl)
min_sw = min(data_sw)
min_pl = min(data_pl)
min_pw = min(data_pw)

Data sepal length
 [[5.1]
 [7. ]
 [6.3]
 [4.9]
 [6.4]
 [5.8]
 [4.7]
 [6.9]
 [7.1]
 [4.6]
 [5.5]
 [6.3]
 [5. ]
 [6.5]
 [6.5]
 [5.4]
 [5.7]
 [7.6]
 [4.6]
 [6.3]
 [4.9]
 [5. ]
 [4.9]
 [7.3]
 [4.4]
 [6.6]
 [6.7]
 [4.9]
 [5.2]
 [7.2]
 [5.4]
 [5. ]
 [6.5]
 [4.8]
 [5.9]
 [6.4]
 [4.8]
 [6. ]
 [6.8]
 [4.3]
 [6.1]
 [5.7]
 [5.8]
 [5.6]
 [5.8]
 [5.7]
 [6.7]
 [6.4]
 [5.4]
 [5.6]
 [6.5]
 [5.1]
 [5.8]
 [7.7]
 [5.7]
 [6.2]
 [7.7]
 [5.1]
 [5.6]
 [6. ]
 [5.4]
 [5.9]
 [6.9]
 [5.1]
 [6.1]
 [5.6]
 [4.6]
 [6.3]
 [7.7]
 [5.1]
 [6.1]
 [6.3]
 [4.8]
 [6.4]
 [6.7]
 [5. ]
 [6.6]
 [7.2]
 [5. ]
 [6.8]
 [6.2]
 [5.2]
 [6.7]
 [6.1]
 [5.2]
 [6. ]
 [6.4]
 [4.7]
 [5.7]
 [7.2]
 [4.8]
 [5.5]
 [7.4]
 [5.4]
 [5.5]
 [7.9]
 [5.2]
 [5.8]
 [6.4]
 [5.5]
 [6. ]
 [6.3]
 [4.9]
 [5.4]
 [6.1]
 [5. ]
 [6. ]
 [7.7]
 [5.5]
 [6.7]
 [6.3]
 [4.9]
 [6.3]
 [6.4]
 [4.4]
 [5.6]
 [6. ]
 [5.1]
 [5.5]
 [6.9]
 [5. ]
 [5.5]
 [6.7]
 [4.5]
 [6.1]
 [6.9]
 [4.4]
 [5.8]
 [5.8]
 [5. ]
 [5. ]
 [6.8]
 [5.1]
 [5.6]
 [6.7]
 [4.8]
 [5.7]
 [6.7]
 [5.1]
 [5.7]
 

In [6]:
#normalisasi sepal length
sl_norm = np.zeros(shape=(data_length,1))

for k in range(data_length):
    sl_norm[k,:] = (data_sl[k] - min_sl) / (max_sl - min_sl)

print('sl_norm\n',sl_norm)

#normalisasi sepal width
sw_norm = np.zeros(shape=(data_length,1))

for k in range(data_length):
    sw_norm[k,:] = (data_sw[k] - min_sw) / (max_sw - min_sw)

print('sw_norm\n',sw_norm)

#normalisasi petal length
pl_norm = np.zeros(shape=(data_length,1))

for k in range(data_length):
    pl_norm[k,:] = (data_pl[k] - min_pl) / (max_pl - min_pl)

print('pl_norm\n',pl_norm)

#normalisasi petal width
pw_norm = np.zeros(shape=(data_length,1))

for k in range(data_length):
    pw_norm[k,:] = (data_pw[k] - min_pw) / (max_pw - min_pw)

print('pw_norm\n',pw_norm)

sl_norm
 [[0.22222222]
 [0.75      ]
 [0.55555556]
 [0.16666667]
 [0.58333333]
 [0.41666667]
 [0.11111111]
 [0.72222222]
 [0.77777778]
 [0.08333333]
 [0.33333333]
 [0.55555556]
 [0.19444444]
 [0.61111111]
 [0.61111111]
 [0.30555556]
 [0.38888889]
 [0.91666667]
 [0.08333333]
 [0.55555556]
 [0.16666667]
 [0.19444444]
 [0.16666667]
 [0.83333333]
 [0.02777778]
 [0.63888889]
 [0.66666667]
 [0.16666667]
 [0.25      ]
 [0.80555556]
 [0.30555556]
 [0.19444444]
 [0.61111111]
 [0.13888889]
 [0.44444444]
 [0.58333333]
 [0.13888889]
 [0.47222222]
 [0.69444444]
 [0.        ]
 [0.5       ]
 [0.38888889]
 [0.41666667]
 [0.36111111]
 [0.41666667]
 [0.38888889]
 [0.66666667]
 [0.58333333]
 [0.30555556]
 [0.36111111]
 [0.61111111]
 [0.22222222]
 [0.41666667]
 [0.94444444]
 [0.38888889]
 [0.52777778]
 [0.94444444]
 [0.22222222]
 [0.36111111]
 [0.47222222]
 [0.30555556]
 [0.44444444]
 [0.72222222]
 [0.22222222]
 [0.5       ]
 [0.36111111]
 [0.08333333]
 [0.55555556]
 [0.94444444]
 [0.22222222]
 [0.5      

In [7]:
#gabungin data input
data_input_ok = np.hstack((sl_norm,sw_norm,pl_norm,pw_norm))
data_target_ok = data_target_np

print('data input\n',data_input_ok)
print('data target\n',data_target_ok)

#save ke csv
np.savetxt("matriks_input.csv",data_input_ok,delimiter=",")
np.savetxt("matriks_target.csv",data_target_ok,delimiter=",")

data input
 [[0.22222222 0.625      0.06779661 0.04166667]
 [0.75       0.5        0.62711864 0.54166667]
 [0.55555556 0.54166667 0.84745763 1.        ]
 [0.16666667 0.41666667 0.06779661 0.04166667]
 [0.58333333 0.5        0.59322034 0.58333333]
 [0.41666667 0.29166667 0.69491525 0.75      ]
 [0.11111111 0.5        0.05084746 0.04166667]
 [0.72222222 0.45833333 0.66101695 0.58333333]
 [0.77777778 0.41666667 0.83050847 0.83333333]
 [0.08333333 0.45833333 0.08474576 0.04166667]
 [0.33333333 0.125      0.50847458 0.5       ]
 [0.55555556 0.375      0.77966102 0.70833333]
 [0.19444444 0.66666667 0.06779661 0.04166667]
 [0.61111111 0.33333333 0.61016949 0.58333333]
 [0.61111111 0.41666667 0.81355932 0.875     ]
 [0.30555556 0.79166667 0.11864407 0.125     ]
 [0.38888889 0.33333333 0.59322034 0.5       ]
 [0.91666667 0.41666667 0.94915254 0.83333333]
 [0.08333333 0.58333333 0.06779661 0.08333333]
 [0.55555556 0.54166667 0.62711864 0.625     ]
 [0.16666667 0.20833333 0.59322034 0.66666667]
 

In [8]:
#inisialisasi parameter
batch_size = 150
input_dimension = 4
hidden_unit = 24
output_dimension = 3
epoch_max = 1000
loss_plot = np.zeros(shape=(epoch_max,1))
t_plot = np.zeros(shape=(epoch_max,1))
error_now = 1000
target_error = 0.0001
i = 0

#ubah ke tensor
data_input_tensor = torch.from_numpy(data_input_ok).float()
data_target_tensor = torch.from_numpy(data_target_ok).float()

In [9]:
# device = torch.device("cuda")
model = torch.load('training_f_1549610711.pt') #ganti nama filenya dengan file bobot hasil training
# model.to(device)
model.eval()
with torch.no_grad():

    loss_fcn = torch.nn.MSELoss()

    learning_rate = 0.1
    for t in range(1):
        y_pred = model(data_input_tensor)
    
        loss = loss_fcn(y_pred,data_target_tensor)

y_pred_np = y_pred.numpy()
error = y_pred_np - data_target_ok
matrix_zeros = np.zeros(4,dtype=int)
benar = 0
salah = 0

#baris = 0
for baris in range (batch_size):
    error_i = np.absolute(error[baris])
    if (error_i <= 0.001 ).all():
        benar = benar + 1
        
    else:
        salah = salah + 1
        
        
print("benar, salah: ",benar,salah)
print("persen benar: ",benar/batch_size*100)
print("Loss: ", loss)
print(y_pred_np)

benar, salah:  0 150
persen benar:  0.0
Loss:  tensor(0.0686)
[[-8.68840218e-02  8.59897733e-02  1.00173724e+00]
 [ 3.75737011e-01  4.88712132e-01  1.46929622e-01]
 [ 1.10261893e+00 -1.71915889e-02 -9.86197367e-02]
 [-1.63314223e-01  2.91632354e-01  8.74223948e-01]
 [ 4.60160255e-01  3.93153638e-01  1.50015175e-01]
 [ 6.60705626e-01  4.27664399e-01 -9.70895588e-02]
 [-9.91667509e-02  1.24460518e-01  9.72629070e-01]
 [ 4.29391205e-01  4.90888745e-01  8.87042657e-02]
 [ 7.96470106e-01  2.95210123e-01 -8.82871673e-02]
 [-1.15206003e-01  1.98290169e-01  9.12995875e-01]
 [ 2.36745477e-01  7.52092779e-01  1.18912570e-02]
 [ 6.21875763e-01  4.52557117e-01 -7.97301605e-02]
 [-5.67240715e-02  1.43988729e-02  1.04062033e+00]
 [ 3.93706083e-01  5.70463538e-01  4.32630926e-02]
 [ 8.73529851e-01  2.31740534e-01 -1.11234345e-01]
 [ 5.19298315e-02 -3.74842286e-02  9.85881090e-01]
 [ 3.13696742e-01  6.07492864e-01  7.49194026e-02]
 [ 8.04265857e-01  3.28775942e-01 -1.26565725e-01]
 [-2.25019455e-03 -2